### ISSUE TITLE
Getting issue in OpenAI key

### ISSUE THREAD

**Issue by hasnainhakim** [sentient-engineering/jobber#8]
Getting Below error

I have added the apikey to env file, change the name from .env.example to .env still same error

C:\Users\hhakim\Desktop\Hasnain_Personal\jobber-main>python -u -m jobber_fsm
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\\Desktop\\jobber-main\jobber_fsm\__main__.py", line 21, in <module>
    asyncio.run(main())
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\\Desktop\\jobber-main\jobber_fsm\__main__.py", line 12, in main
    State.PLAN: PlannerAgent(),
                ^^^^^^^^^^^^^^
  File "C:\Users\\Desktop\\jobber-main\jobber_fsm\core\agent\planner_agent.py", line 15, in __init__
    super().__init__(
  File "C:\Users\\Desktop\\jobber-main\jobber_fsm\core\agent\base.py", line 41, in __init__
    self.client = wrap_openai(openai.Client())
                              ^^^^^^^^^^^^^^^
  File "C:\Users\hhakim\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by Amoghk04** [comment]
run the following commands, if using Linux

`export OPENAI_API_KEY="your_api_key"`
`source ~/.bashrc`

If using windows, then run this in the powershell
`[System.Environment]::SetEnvironmentVariable("OPENAI_API_KEY", "your_api_key", "User")
`
hope this works
